apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: {{ .Values.configmap.name }}
          configMap:
            name: {{ .Values.configmap.name }}
      containers:
      - name: selekt
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        env:
          - name: SELEKT_ADMIN
            value: "admin@selekt.com"
          - name: SELEKT_ADMIN_PASSWORD
            value: "admin"
          - name: SELEKT_APP_LOG_LEVEL
            value: 'debug'
          - name: SELEKT_WEB_LOG_LEVEL
            value: 'warn'
          - name: SELEKT_CONNECTIONS__pgdemo__name
            value: 'Postgres demo'
          - name: SELEKT_CONNECTIONS__pgdemo__driver
            value: 'postgres'
          - name: SELEKT_CONNECTIONS__pgdemo__host
            value: 'selekt-postgresql'
          - name: SELEKT_CONNECTIONS__pgdemo__database
            value: 'postgres'
          - name: SELEKT_CONNECTIONS__pgdemo__username
            value: 'selekt'
          - name: SELEKT_CONNECTIONS__pgdemo__password
            value: 'selekt'
          - name: SELEKT_CONNECTIONS__pgdemo__multiStatementTransactionEnabled
            value: 'true'    
          - name: SELEKT_CONNECTIONS__pgdemo__idleTimeoutSeconds
            value: '86400'           