apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
  - name: tcp-rule-selekt
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Chart.Name }}