services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: selekt
      POSTGRES_PASSWORD: selekt
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
